x-app: &app
  build:
    context: .
    args:
      RUBY_VERSION: '3.2.4'
      PG_MAJOR: '17'
      GRADLE_VERSION: "8.7"
      DISTRO_NAME: "bookworm"
  image: trexample-ruby:1.0.0
  privileged: true
  environment: &env
    RAILS_ENV: ${RAILS_ENV:-development}
  tmpfs:
    - /tmp:exec
    - /app/tmp/pids

x-backend: &backend
  <<: *app
  stdin_open: true
  tty: true
  volumes:
    - ..:/app:cached
    - ./../.bundle:/usr/local/bundle
    - ./.psqlrc:/root/.psqlrc:ro
    - ./.bashrc:/root/.bashrc:ro
    - history:/usr/local/hist
    - gradle:/home/gradle/.gradle
  environment: &backend_environment
    <<: *env
    DATABASE_URL: postgres://postgres:postgres@postgres:5432
    PULSAR_URL: pulsar://pulsar:6650
    BOOTSNAP_CACHE_DIR: /usr/local/bundle/_bootsnap
    XDG_DATA_HOME: /app/tmp/cache
    HISTFILE: /usr/local/hist/.bash_history
    PSQL_HISTFILE: /usr/local/hist/.psql_history
    IRB_HISTFILE: /usr/local/hist/.irb_history
    EDITOR: vi
    DATABASE_CLEANER_ALLOW_REMOTE_DATABASE_URL: true
    TRUFFLERUBYOPT: --jvm --experimental-options --cexts-lock=false --cexts-panama
  depends_on: &backend_depends_on
    postgres:
      condition: service_healthy

services:
  backend:
    <<: *backend
    command: bundle exec rails server -b 0.0.0.0 -e production
    ports:
      - "3001:3000"

  pulsar:
    image: apachepulsar/pulsar:3.3.3
    volumes:
      - pulsar-data:/pulsar/data
      - pulsar-conf:/pulsar/conf
    environment:
      PULSAR_STANDALONE_USE_ZOOKEEPER: 1
    command: bin/pulsar standalone
    ports:
      - "6650:6650"
      - "8080:8080"

  postgres:
    image: postgres:17-alpine
    volumes:
      - .psqlrc:/root/.psqlrc:ro
      - postgres-data:/var/lib/postgresql/data
      - history:/user/local/hist
    environment:
      PSQL_HISTFILE: /user/local/hist/.psql_history
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: pg_isready -U postgres -h 127.0.0.1
      interval: 5s

  rails:
    <<: *backend
    command: echo "rails"

volumes:
  history:
  postgres-data:
  pulsar-data:
  pulsar-conf:
  gradle:
